/*
@TargetNode='localhost'
@GeneratedBy=olivi
@GenerationDate=05/05/2025 22:37:21
@GenerationHost=MSI
*/

instance of MSFT_RegistryResource as $MSFT_RegistryResource1ref
{
ResourceID = "[Registry]Registydemo";
 ValueName = "TestValue";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\ExampleKey1";
 ValueType = "String";
 ModuleVersion = "2.12.0.0";
 ValueData = {
    "TestData"
};
 ModuleName = "PSDscResources";
 SourceInfo = "C:\\work\\DSC-Azure-machine-config-demo\\DSC\\demo.dsc.ps1::8::5::Registry";
 Ensure = "Present";
 ConfigurationName = "demoDevTo";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="olivi";

                        GenerationDate="05/05/2025 22:37:21";

                        GenerationHost="MSI";

                        Name="demoDevTo";

                    };
